<testsuite errors="0" failures="1" name="unittest.suite.TestSuite" tests="5" time="0.001">
  <testcase classname="__main__.MzpTest" name="test_Alice_tab_かきくきこをNormal_tab_かきくけことして返す" time="0.0010"></testcase>
  <testcase classname="__main__.MzpTest" name="test_gab_km_tab_あいうえおをNormal_tab_あいうえおとして返す" time="0.0000"></testcase>
  <testcase classname="__main__.MzpTest" name="test_ハッシュタグ付きのTweetをハッシュタグ付きとして扱う" time="0.0000"></testcase>
  <testcase classname="__main__.MzpTest" name="test_メンションTweetをMention_tab_tweetbodyとして返す" time="0.0000">
    <failure type="builtins.AssertionError">'Mention\tふげ @Alice ひげ' != 'Normal\tふげ @Alice ひげ'
- Mention	ふげ @Alice ひげ
+ Normal	ふげ @Alice ひげ

  File "C:\Python32\lib\unittest\case.py", line 387, in _executeTestPart
    function()
  File "mzp_test.py", line 26, in test_メンションTweetをMention_tab_tweetbodyとして返す
    self.assertEqual("Mention\tふげ @Alice ひげ", result)
  File "C:\Python32\lib\unittest\case.py", line 643, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Python32\lib\unittest\case.py", line 1060, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Python32\lib\unittest\case.py", line 511, in fail
    raise self.failureException(msg)
    </failure>
  </testcase>
  <testcase classname="__main__.MzpTest" name="test_リプライTweetをReply_tab_tweetbodyとして返す" time="0.0000"></testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
